### ISSUE TITLE
Does the DynamO can do 2D simulations?

### ISSUE THREAD

**Issue by huijun-zhang** [toastedcrumpets/DynamO#53]
Dear all,
As the title said, does the dynamo can do 2D simulations? The option "--zero-vel 0/1/2" can set the velocity on one direction to zero, so it seems to be able to run a 2D simulation. I think this maybe suitable for HardSphere system which does not need -T (Thermostat) to control temperature. But for system like SquareWell, we must use -T to control the system's temperature. It will reset the velocity at x, y, and z directions.
I tried "dynamod config.start.xml -T 1.0 --zero-vel 2 -Z --zero-com -o config.init.xml", but it does not work.
My question is how can I do a 2D simulation of SW system if the DynamO can? 
Thank you very much!

Your sincerely,
Huijun Zhang

**Comment by toastedcrumpets** [comment]
As listed on the manual for the Andersen thermostat:
http://dynamomd.org/index.php/reference#typeandersen


   - Dimensions (*attribute*): A number indicating how many dimensions of
   the particles are to be thermostatted. The default is all (=3). If set to
   2, the z dimension is not affected by the thermostat, and if set to 1,
   neither the y or z-dimensions are affected.

You may need to make this change by hand in the configuration file.
Kind regards,
Marcus

Dr Marcus Campbell Bannerman
Materials & Chemical Engineering Research Group
Lecturer in Engineering, University of Aberdeen
Office: +44 (0)1224 27 4480
Email: m.campbellbannerman@abdn.ac.uk
Web: http://www.abdn.ac.uk/engineering/profiles/m.campbellbannerman

**Comment by huijun-zhang** [comment]
Dear Bannerman,
Thank you very much for your response. I have added the dimension="2" to the Thermostat after "dynamo config.start.xml -T 1.0 -Z --zero-vel 2 -o config.init.xml", but the output temperature continually increased. I don't know why?
Best regards,
Huijun

**Comment by toastedcrumpets** [comment]
Can you send me the configuration file?

**Comment by huijun-zhang** [comment]
Hi Marcus,
Because the file is too large to show here, I have sent it to your Email. I am really confused and frustrated, and looking forward to your response.

Best regards

**Comment by toastedcrumpets** [comment]
There are a couple of issues with your configuration.

First, you've started it with bad capture maps. When I load this configuration I get:
```
NbListScheduler: Checking Interaction "ABInteraction" for invalid states
Interaction[AAInteraction]: Particle 316 and Particle 429 are inside the well
  with an inner hard core at 1.3 but they are at a distance of 1.3
...
Interaction[BBInteraction]: Particle 3262 and Particle 6375 are registered as
  being outside the well at a distance of 1.3 but they are at a distance of 1.15432
NbListScheduler: Over 100 warnings of invalid states, further output was
  suppressed (total of 2793 warnings detected)
```

I got rid of these errors by deleting the CaptureMap tags in the configuration file (which forces DynamO to rebuild them).

Second, your ABInteraction has an Elasticity of 1.13. As this is greater than one it will continuously pump energy into your system, which the thermostat will attempt to remove but the steady state will end up somewhere higher than the thermostat set point. The Andersen thermostat does not ridgidly constrain the temperature. 

I don't think there's any errors here, just a bad set up of the configuration. DynamO is giving you the appropriate warnings (2793 of them!) so I'll close this as *solved* but feel free to ask more questions about this config if needed. I'm not sure what it is you're trying to simulate?
Kind regards,
Marcus

**Comment by huijun-zhang** [comment]
Hi Marcus,
Thank you very much! Great, it is now work robustly. 

Warm wishes,
Huijun
