### ISSUE TITLE
Error at loading dynavis

### ISSUE THREAD

**Issue by h-dashti** [toastedcrumpets/DynamO#56]
My Os is ubuntu 14.04. When i type 
`dynavis config.start.xml -c 1000000`
i catch these errors:

> Simulation: Initialising Systems
> GL-Context 0x7faf8c5b0b70: Created a new OpenGL context
> GL-Context 0x7faf8c5b0b70: OpenGL version 3.3
> 
> Coil caught an exception while performing its tasks
> Exception thrown in [build] (/home/mjki2mb2/CTest/DynamO/src/magnet/magnet/GL/shader/detail/shader.hpp:540)
> Geometry shaders are not supported by your OpenGL driver.
>  Shader source:
> layout(points) in;
>  layout(triangle_strip) out;
>  layout(max_vertices = 4) out;
>  uniform mat4 ProjectionMatrix;
>  uniform mat4 ViewMatrix;
>  in vec4 color[];
>  smooth out vec2 texCoord;
>  flat out vec4 frag_color;
>  void main() {
>    frag_color = color[0];
>    texCoord = vec2(0.0, 1.0);
>    gl_Position = ProjectionMatrix * (ViewMatrix * vec4(-1.0, -1.0, 0.0, 1.0));
>    EmitVertex();
>    texCoord = vec2(0.0, 0.0);
>    gl_Position = ProjectionMatrix * (ViewMatrix * vec4(-1.0, +1.0, 0.0, 1.0));
>    EmitVertex();
>    texCoord = vec2(1.0, 1.0);
>    gl_Position = ProjectionMatrix * (ViewMatrix * vec4(+1.0, -1.0, 0.0, 1.0));
>    EmitVertex();
>    texCoord = vec2(1.0, 0.0);
>    gl_Position = ProjectionMatrix * (ViewMatrix * vec4(+1.0, +1.0, 0.0, 1.0));
>    EmitVertex();
>    EndPrimitive();
>    }
> 
> Main(): Exception thrown in [addWindow] (/home/mjki2mb2/CTest/DynamO/src/coil/coil/coilMaster.hpp:51)
>   Coil failed to add the window as the main render thread died
> Main(): For a stack trace please run the debugging executables.
> Segmentation fault (core dumped)

**Comment by toastedcrumpets** [comment]
This was an issue with DynamO and open source (mesa) drivers. This was fixed one week ago.

The build servers are currently creating new packages (http://cdash.dynamomd.org/index.php?project=DynamO)
Once they've built them, they will be available at the download page:
http://dynamomd.org/index.php/download

Alternatively the ubuntu PPA already has the fixed packages.

Kind regards,
Marcus
