### ISSUE TITLE
Inelastic collapse with Newtonian Dynamics

### ISSUE THREAD

**Issue by sudhirnpathak** [toastedcrumpets/DynamO#57]
Dear Developer,

First of all, Thanks for this wonderful software package. 

I am trying to simulate monocomponent inelastic hard spheres. Due to inelastic collapse, simulation does not proceed after some time. In the documentation, I can see two methods implemented to avoid inelastic collapse but for the NewtonianGravity dynamics. I think it can be easily implemented for Newtonian too, leading to greater versatility of dynamO. Please let me know what you think?

Thanks
Sudhir

**Comment by toastedcrumpets** [comment]
Hi,
I agree. 
For the time-being, could you try using the NewtonianGravity dynamics, but with a gravity of zero?
Marcus

**Comment by sudhirnpathak** [comment]
Thanks Marcus,

I tried what you suggested and its working well. Please update here when this feature is implemented for Newtonian dynamics.

Also, Could you please clarify one more point ? Isn't the illegal overlaps of hard spheres taken into account be default? Or do we need to use --check option ?

Thanks
Sudhir

**Comment by toastedcrumpets** [comment]
By default, after a simulation the code checks for any errors using the neighbour list. The --check option of dynamod is much slower as it doesn't use the neighbour list and fully checks all pairings of particles.

Normally, a user should never need to use the --check option. Its just for the developers to check the neighbour list implementation.
Marcus
