### ISSUE TITLE
Rotational energy output

### ISSUE THREAD

**Issue by sudhirnpathak** [toastedcrumpets/DynamO#58]
Hi Marcus,

In the issue #23, I could see discussion about adding the rotational energy in output, separately from the current temperature. I do not find it implemented. Please advice me on this.

Also, it would be very useful if we have the option of outputting certain quantities with time. For example, I would like to output translational and rotational energy separately at regular intervals of time.

Thanks
Sudhir

**Comment by toastedcrumpets** [comment]
Issue #23 has the current status of that work (incomplete). 

For customised properties with time, I would suggest using the snapshots feature, then processing the snapshots yourself to extract any properties you like from the configuration.
Kind regards,
Marcus
