### ISSUE TITLE
Implement the entire version of the PRIME20 potential

### ISSUE THREAD

**Issue by jingjieyeo** [toastedcrumpets/DynamO#59]
I believe a lot more information about the PRIME20 potential has been published recently:
[http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004258](url)

Would it be possible to update Dynamo to include all these parameters?

**Comment by toastedcrumpets** [comment]
Sure, you can edit DynamO and add these parameters. The current implementation is in src/dynamo/dynamo/interactions/PRIME.cpp and the .hpp file too.

From what I remember, the PRIME20 has unpublished information on the hydrogen backbone interactions which prevents it from being fully implemented (see the header file for more information). Although this new article updates some of the constants used I think it still misses out the hydrogen bonding. If you want to try to figure this out, be my guest and I'll support you, but I (and a collaborator) have wasted enough time with this potential.

**Comment by toastedcrumpets** [comment]
Sorry if I sound a bit harsh, but it was quite frustrating to work on a complex potential like this, then to find key parameters are missing.

**Comment by jingjieyeo** [comment]
I fully understand and empathize with you, it is also terribly disappointing for me to hear that. So technically the version implemented in Dynamo corresponds to the PRIME20-like potential as published in Gil's thesis?

**Comment by toastedcrumpets** [comment]
Yeah that is correct. I have not progressed on it further since then. I'll close the comment, but we can continue to use it to discuss the potential/your issues if needed.
