### ISSUE TITLE
Particle ID order affects Invalid States

### ISSUE THREAD

**Issue by scmartin** [toastedcrumpets/DynamO#61]
I've developed a python program to insert a particle into a bulk hard sphere configuration generated with dynmod. using pythons _xml_ module the newly added particle is at the end of the list, but my program assigns it the index of zero to make other processing simpler.

When I use the configuration in dynarun, I noticed that when it gets to NbListScheduler, the order of the particles in the configuration file matters.

If the new particle with ID=0 is at the end, where python adds it, I get warnings about particle overlaps such as
_Interaction[fluidwall]: Particle 0 and Particle 9630 have entered the core at
  10.5 and are at a distance of 10_

If I simply move the particle to the beginning of the ParticleData section, the warnings go away.

I could just change my program to reindex the particles, but I think that the ID order shouldn't matter when testing for bad initial configurations.

**Comment by toastedcrumpets** [comment]
The indices in the configuration file are ignored on load, only the order in the file matters. What your describing shouldn't be a problem unless there is other information in the configuration file which uses the indices. Can you upload the configuration file as a github gist so I can take a look?

**Comment by scmartin** [comment]
Sorry for the slow response. Here's a gist with a configuration that throws the warnings I described if particle 0 is at the end, but not if it is at the beginning of ParticleData.

<script src="https://gist.github.com/scmartin/7c448b5a868f20a43e9ed14f4878e731.js"></script>

**Comment by toastedcrumpets** [comment]
OK so this is because of what I said. 

DynamO, on loading a config file, ignores the index attribute, and just allocates indices according to the order in what the Particle tags appear. The only reason why the index attribute exists is to help you identify the number of the particle in the file. I'm not sure if this is intuitive or not, but it makes it very easy to delete and add particles in simple configs.

Taking a look at your config file, the config file has interactions specially set for particle 0 (see below). So moving the Particle 0 tag to the end actually changes it to Particle index 500 (and changes particle 1 to particle 0), thus changing its interactions and causing overlaps.
```<DynamOconfig version="1.5.0">
  <Simulation>
    <Scheduler Type="NeighbourList">
      <Sorter Type="BoundedPQMinMax3" />
    </Scheduler>
    <SimulationSize x="103.688412662" y="103.688412662" z="62.0" />
    <Genus>
      <Species Mass="1" Name="Bulk" Type="Point">
        <IDRange End="500" Start="1" Type="Ranged" />
      </Species>
      <Species Mass="100" Name="Wall" Type="Point">
	<IDRange Type="List">
	  <ID val="0" />
	</IDRange>
      </Species>
    </Genus>
    <BC Type="PBC" />
    <Topology />
    <Interactions>
      <Interaction Diameter="1" Name="Bulk" Type="HardSphere">
        <IDPairRange Type="Single"><IDRange End="500" Start="1" Type="Ranged" /></IDPairRange>
      </Interaction>
      <Interaction Diameter="15.5" Name="fluidwall" Type="HardSphere">
	<IDPairRange Type="Pair">
	  <IDRange End="500" Start="1" Type="Ranged" />
	  <IDRange Type="List">
	    <ID val="0" />
	  </IDRange>
	</IDPairRange>
      </Interaction>
      <Interaction Diameter="1" Name="wall" Type="HardSphere">
	<IDPairRange Type="Self">
	  <IDRange Type="List">
	    <ID val="0" />
	  </IDRange>
	</IDPairRange>
      </Interaction>
    </Interactions>
```

**Comment by toastedcrumpets** [comment]
I'm closing as this is behaviour that I expect, but I'd like to hear your thoughts on what is intuitive or makes more sense!

**Comment by scmartin** [comment]
I think I understand what you are saying, but I think using the internally generated index could be difficult. First, is it 0-indexed (I assume so as it's written in C++) or 1-indexed? If you use the internal index rather than the user defined ID, the IDRange seems misleading, as it refers to an internal index implied by the particle order, rather than the ID the user specified. I saw that tutorial 3 mentions this on the website, but it would be useful in the Config File Format reference under IDRange as well. I'm not sure what the best approach is; using the user provided ID certainly could cause problems if you rely on the ID's being integers to use them in indexing vectors and such.

**Comment by toastedcrumpets** [comment]
Yes, its zero indexed. I also agree that its misleading to give freedom in specifying IDRanges, but have particle index implicit. I agree the config can be updated to fix this.
How about this idea, particles don't have an index, but a type number? Then indexes can be completely hidden away internally, and users just worry about getting the type right?

**Comment by scmartin** [comment]
I like the type number (or even type name) idea. You might then be able to add the ability to specify species or interactions with the type(s) in the ParticleData section. I think this would still provide the benefit of each particle not needing to carry around all it's own info but reference mass, particle type, and interactions with functional mappings using the type number or type name in each particles ID attribute.
