### ISSUE TITLE
Few question about Dynamo

### ISSUE THREAD

**Issue by Laudarisd** [toastedcrumpets/DynamO#67]
Hello Dynamo group, I hope its an active repo.

I found this repo interesting and willing to include in my research with citation.

I successfully compiled this software in my Linux pc and successfully passed all test in make test section.

Before doing simulation, I would like to ask few questions:
1) Can I change molecules to sperical granular particles in video 1? Any hint to include mixed types(2 types) of particles in config xml file with granular properties like restitution , friction, stress, strain, pressure etc? 
2) Can I export data to text or csv files depending on particles type 1 and type 2?
3) I am trying to do Less Edwards Boundary condition simulation with sperical granular particles, (eg. first video in webpage) is it possible to do it in Dynamomd?

THank you.

**Comment by toastedcrumpets** [comment]
Hi,
Answering your questions, yes you can do all this, but you will have to learn how to edit and use XML files, which are the configuration files.

1. I'm not sure what you mean video 1 exactly, but you can mix all boundary conditions with all particles (so Lees-Edwards with granular particles).
2. Yes, you can, just export all particle positions but filter the IDs to capture type 1 or type 2. "Types" in DynamO are called Species, and you just make the first lot of particles one Species, then the last another. You will want to do something like this https://www.dynamomd.com/index.php/tutorialA#ExampleMakinganXYZPositionFile but add filtering.
3. Ah, ok, yes, you can do Lees-Edwards with anything. Just change the boundary condition in the config file to Lees-Edwards. 

I would say that you should see the different examples of dynamod, and just mix them together to make whatever system you need. Please give it a go and if you get stuck come back here. I'll close the question as its not an "issue" but I will still reply to any questions.

**Comment by Laudarisd** [comment]
Thank you so much for your reply. I will try t edit xml files. I was talking about the vide from you webpage about snomen molucules which is like a simulation of a particles pack. Would you let me know the main configuration xml file path for snomen molucules simulation which is like a pack ? video link is here:https://youtu.be/zAC4PgtUwU4

**Comment by toastedcrumpets** [comment]
That system is made using dynamod mode 27.
```
$ ./dynamod  -m 27 --help
...
  27: Crystal pack of snowmen molecules
       --i1 : Picks the packing routine to use [0] (0:FCC,1:BCC,2:SC)
       --f1 : Inelasticity [1.0]
       --f2 : Size ratio [1.0]
       --f3 : Mass ratio [size_ratio^3]```

Once you make the system at low density, you will want to compress it to reach higher densities (you cannot make it directly at high densities using dynamod, the particles will end up overlapping).
Compression dynamics are covered in this tutorial: https://www.dynamomd.com/index.php/tutorial5

Hope this helps you get started!
