### ISSUE TITLE
Compiling Dynavis

### ISSUE THREAD

**Issue by jingjieyeo** [toastedcrumpets/DynamO#70]
I am trying to compile Dynamomd with dynavis on Ubuntu 18.04, I noticed that the default CMakeLists from GitHub currently set(VISUALIZER_SUPPORT FALSE) so I commented that to make sure the visualizer compiles and the visualizer dependencies were satisfied. 

However, subsequently when I tried to compile, I had an error about no matching function for call to coil::CLGLWindow:: CLGLWindow

May I know how I can potentially resolve this issue and obtain dynavis? Everything else compiles and runs perfectly fine if I left out the visualizer.

Thank you!
JJ

**Comment by toastedcrumpets** [comment]
Hi,
The current master builds have a broken visualiser. I was completely reworking this to use SDL2 and some more modern GUI's than GTKMM3.

Can you try this d486c37e22712dc6394de7ed4e055a5bfc4fc457 build? Certainly the last stable release had a working visualiser too if you want to try that tag.

**Comment by jingjieyeo** [comment]
Thanks for the information, I tried compiling with the last stable release and ran into an error of "stator/xml.hpp: No such file or directory", is there something else that I'm missing?

**Comment by toastedcrumpets** [comment]
Did you clone all the submodules recursively? Stator is in a separate git
submodule.

**Comment by jingjieyeo** [comment]
My apologies but I don't seem to be getting it right. I tried
`git clone --recurse-submodules --branch dynamo-1-7-4 https://github.com/toastedcrumpets/DynamO.git
`
But now I get the error:
```
Cloning into 'DynamO'...
remote: Enumerating objects: 53470, done.
remote: Counting objects: 100% (356/356), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 53470 (delta 200), reused 271 (delta 181), pack-reused 53114
Receiving objects: 100% (53470/53470), 23.56 MiB | 28.55 MiB/s, done.
Resolving deltas: 100% (31976/31976), done.
Note: checking out '2a8d290ba0fd01f524042c1524271b2bd970717d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'extern/stator' (https://github.com/toastedcrumpets/stator.git) registered for path 'extern/stator'
Cloning into '/home/jingjieyeo/Downloads/DynamO/extern/stator'...
remote: Enumerating objects: 3879, done.        
remote: Counting objects: 100% (74/74), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 3879 (delta 72), reused 70 (delta 70), pack-reused 3805        
Receiving objects: 100% (3879/3879), 1.82 MiB | 19.24 MiB/s, done.
Resolving deltas: 100% (3017/3017), done.
Submodule path 'extern/stator': checked out '13a1945e9e33fddcca09dce23d25b30c8be5d4e0'
Submodule 'extern/eigen' (https://github.com/RLovelett/eigen.git) registered for path 'extern/stator/extern/eigen'
Cloning into '/home/jingjieyeo/Downloads/DynamO/extern/stator/extern/eigen'...
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path '/home/jingjieyeo/Downloads/DynamO/extern/stator/extern/eigen' failed
Failed to clone 'extern/eigen'. Retry scheduled
Cloning into '/home/jingjieyeo/Downloads/DynamO/extern/stator/extern/eigen'...
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path '/home/jingjieyeo/Downloads/DynamO/extern/stator/extern/eigen' failed
Failed to clone 'extern/eigen' a second time, aborting
Failed to recurse into submodule path 'extern/stator'

```

**Comment by jingjieyeo** [comment]
Realized it didn't matter that other submodules were not cloned, dynavis compiled correctly now, really appreciate your help and guidance!
