### ISSUE TITLE
Dynarun with multiple threads

### ISSUE THREAD

**Issue by jingjieyeo** [toastedcrumpets/DynamO#71]
I am currently attempting to reproduce the 2-species example in the manual, but with hardsphere interactions and setting Dynarun with either the -N and --n-threads option. However, there does not seem to be any difference, all the simulations simply run on a single thread. Is there something that I may be missing?

**Comment by toastedcrumpets** [comment]
Parallel computation only works with replica exchange, single systems are not able to be run in parallel at this time, sorry.
